spring.application.name=boot-oauth
server.port = 8090

spring.security.oauth2.client.registration.github.client-id = Ov23li8TC9Us4Tz56J58
spring.security.oauth2.client.registration.github.client-secret = 275e4027e74e965c8c9fcd71f42b4d6ebb856205